### ISSUE TITLE
Weird appearance of plasmoid checkboxes with Materia plasma style

### ISSUE THREAD

**Issue by hexclover** [PapirusDevelopmentTeam/materia-kde#111]
If I enable the Materia/Materia Color *plasma style*, the checkboxes in *plasma widgets* get a strange appearance when checked, which looks like “an unchecked checkbox stacking on top of a checked one”; if I press my mouse button on it (w/o releasing), the appearance temporarily becomes normal. This is shown in the GIF animation below:

![simplescreenrecorder-2021-03-17_13 09 20](https://user-images.githubusercontent.com/47456195/112741770-032eff00-8fbb-11eb-9b6a-55c64570c109.gif) 

If I switch to one of the builtin plasma styles (Breeze{,Dark,Light}, Air, Oxygen), there is no such problem. Additionally, there are no problems with checkboxes in applications.

> Operating System: Arch Linux
> KDE Plasma Version: 5.21.3
> KDE Frameworks Version: 5.80.0
> Qt Version: 5.15.2
> Kernel Version: 5.11.9-zen1-1-zen
> OS Type: 64-bit
> Graphics Platform: X11

**Comment by varlesh** [comment]
checkbox on plasma draw on buttons... and all fine, but I'm have problem with slider on Latte Dock (((
Button draw as laer on layer:
1. Normal
2. + Hover
3. + Focus
4. Pressed

If used transparent buttons, like as Materia style we have problem for latte slider, because Plasma devs don't want fix bug 
with Button Background color:
https://bugs.kde.org/show_bug.cgi?id=422043
![image](https://user-images.githubusercontent.com/8083855/112743499-f43f5100-8fa8-11eb-8c87-ed5a2150df12.png)

**Comment by varlesh** [comment]
@psifidotos maybe better use another slider style? Without button

**Comment by varlesh** [comment]
i don't know how fix this for Materia Color...
