### ISSUE TITLE
"Add Network Folder" In Dolphin is not visible

### ISSUE THREAD

**Issue by ilvipero** [PapirusDevelopmentTeam/materia-kde#113]
I found a cosmetic issue with the theme, using Ubuntu Studio 21.04.
As shown in the linked screenshots, "Add Network Folder" In Dolphin is not visible, actually it is barely readable. Once I mouse over it, it becomes visible though as the highlight color is white.

https://imgur.com/a/Iyd36If

**Comment by eeickmeyer** [comment]
Confirmed that this does, indeed, occur on the Materia kvantum theme, but not MateriaDark or MateriaLight.

**Comment by varlesh** [comment]
what you Dolphin  version use?

**Comment by varlesh** [comment]
i think [this commit](https://github.com/KDE/dolphin/commit/b1cadeba939155282a9fadf7d7b025d6529c489e) move button to URL place & this solve problem:
![image](https://user-images.githubusercontent.com/8083855/114504232-9c0e7d00-9c3f-11eb-8ac3-14442229efb3.png)
Anyway it's not Materia bug, because they use QPushButton instead QToolButton on Toolbar widget
