### ISSUE TITLE
Provide lockscreen theme

### ISSUE THREAD

**Issue by dianlujitao** [PapirusDevelopmentTeam/materia-kde#117]
It turns out that materia doesn't provide a lock screen theme so that the system uses the default breeze theme for lockscreen.

**Comment by varlesh** [comment]
i try modify Breeze code to Materia style... but don't like this, because code overloaded and have more unnecessary things
![image](https://user-images.githubusercontent.com/8083855/122511751-cbaf7c00-d018-11eb-9d69-7873e13954c0.png)

**Comment by varlesh** [comment]
i think need present style as sddm theme and remove blur, moved clock to panel...
About Media Controls, i think better move this to top right like as widget

**Comment by varlesh** [comment]
New version:
![image](https://user-images.githubusercontent.com/8083855/122544868-463ec280-d03e-11eb-9adb-f2a27cd99f60.png)

**Comment by varlesh** [comment]
done...  Darker version very hard doing, because lockscreen used colors from plasma theme and Materia not have light colors for that.
Materia Light
![lockscreen](https://user-images.githubusercontent.com/8083855/122628483-4931c580-d0c7-11eb-90e2-16386591c174.png)
Materia Dark
![image](https://user-images.githubusercontent.com/8083855/122628417-f0622d00-d0c6-11eb-9f1f-f6e066f4e961.png)
If you find errors - welcome ))
