### ISSUE TITLE
Window decoration resize issue

### ISSUE THREAD

**Issue by burak-aydin** [PapirusDevelopmentTeam/materia-kde#131]
Resizing windows from top bar is not possible while using materia window decoration. The first screenshot is breeze behavior and second materia. Is it possible to get the same behavior?

![Screenshot_20211217_004539](https://user-images.githubusercontent.com/45029830/146453959-cb95a8ee-e509-4eb5-acfa-8bcfaaae9503.png)

![Screenshot_20211217_004628](https://user-images.githubusercontent.com/45029830/146453897-a47bba4b-b934-43cb-a110-bfe199a860a2.png)

**Comment by varlesh** [comment]
Not confirm this:
![image](https://user-images.githubusercontent.com/8083855/146463428-33bdd35c-bafd-40ff-9899-11eabc3792c9.png)

**Comment by burak-aydin** [comment]
found the issue, turns out if window border size was set to none resize doesnt work with this. In breeze even if the border size is set to none it works. Very minor issue.

**Comment by varlesh** [comment]
I think it's aurorae bug or limitation. Because formaly aurorae not have config for top border.
https://github.com/KDE/kwin/blob/master/src/plugins/kdecorations/aurorae/theme-description#L125-L127
With non borders option - it's worked for left, right, bottom, left-top, right-top, bottom-left and bottom-right... but not top

**Comment by varlesh** [comment]
https://bugs.kde.org/show_bug.cgi?id=417716

**Comment by burak-aydin** [comment]
i see thanks for the information.
