### ISSUE TITLE
Qt6 update?

### ISSUE THREAD

**Issue by enkeyz** [PapirusDevelopmentTeam/materia-kde#134]
Can we expect a Qt 6 update?

**Comment by maltejur** [comment]
Using [qt6ct](https://github.com/trialuser02/qt6ct) and [kvantum](https://github.com/tsujan/Kvantum), everything works perfect with qt6.

![Screenshot_20220216_123806](https://user-images.githubusercontent.com/48161361/154257472-a4af8a05-3f8c-49f4-95cf-17b43c90ece4.png)

Still weird that it doesn't work with the KDE settings menu and you have to use qt6ct though.

**Comment by Mrfiregem** [comment]
Can confirm that setting the theme to Materia in KDE settings doesn't work for qt6 programs, but using qt6ct with the kvantum theme and setting `QT_QPA_PLATFORMTHEME=qt6ct` works perfectly for both qt5 and qt6 programs.

**Comment by spikespaz** [comment]
Can someone print out all of their relevant environment variables? It isn't working for me.

**Comment by SmartFinn** [comment]
`qt6-style-kvantum` package added to [`ppa:papirus/papirus`](https://launchpad.net/~papirus/+archive/ubuntu/papirus) for Ubuntu 22.04 (not sure that working, because `qt6ct` package is missing), Ubuntu 23.04, and Ubuntu 23.10. See https://github.com/PapirusDevelopmentTeam/arc-kde/issues/133#issuecomment-1785365698

**Comment by gijsrrr** [comment]
Thanks @SmartFinn for your persistent dedication to this project - As an long time Materia-lover: Thank you!
