### ISSUE TITLE
The screen locker is broken on Plasma 5.25.2 after latest update

### ISSUE THREAD

**Issue by Dkoeddnsnp** [PapirusDevelopmentTeam/materia-kde#142]
After latest upgrade from git I sometimes while trying to unlock my system on Plasma 5.25, I have a message "The screen locker is broken...".
![Screenshot_20220630_202510](https://user-images.githubusercontent.com/66845002/176741247-817f7ec6-3837-40bb-a2f6-6d87e2f5c0fc.png)

The isssue is gone after downgrading the materia-kde git pacckage to materia-kde 20220607-1 from repos.

The output for **/usr/lib64/kscreenlocker_greet --testing** gives me:
`file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/components/VirtualKeyboard.qml:22:1: Type InputPanel unavailable
qrc:/QtQuick/VirtualKeyboard/content/InputPanel.qml:127:5: Type Keyboard unavailable
qrc:/QtQuick/VirtualKeyboard/content/components/Keyboard.qml:38:1: module "QtQuick.VirtualKeyboard.Plugins" is not installed
Locked at 1656610484
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/PanelUI.qml:140: TypeError: Cannot read property 'shortName' of undefined
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
`

The output with downgraded version:
`Locked at 1656610722
file:///usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/UserList.qml:43:9: Unable to assign [undefined] to bool
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
`

**Comment by varlesh** [comment]
Hm... I'm not seen critical messages on your logs. VirtualKeyboard disabled (on Materia) very long time ago.

> `TypeError: Cannot read property 'shortName'`

It's Keyboard indicator from `plasma.workspace.components 2.0`

I'm use KDE Neon with plasma 5.25.1 X11 and all worked fine:
![image](https://user-images.githubusercontent.com/8083855/176798204-22bf55d2-8dc7-482a-b22b-43ac33ca735c.png)

**Comment by varlesh** [comment]
They change api again? What are they doing, do you understand?

**Comment by varlesh** [comment]
Now i'm upgrade to 5.25.2 and not seen errors:
![image](https://user-images.githubusercontent.com/8083855/176799877-18071cfd-038b-4f80-b398-346e4b147524.png)

Maybe it's Wayland bug? You try X11?

**Comment by Dkoeddnsnp** [comment]
This issue is not 100% reproducible. It happens in 10-20 locked screens. I will try x11.

**Comment by varlesh** [comment]
KDE developers have started some kind of mania to break everything and rewrite the api, almost every month. A [similar situation](https://github.com/varlesh/org.kde.plasma.compact-shutdown/issues/19) is now observed with my Compact Shutdown widget. Thank God I didn't use the Plasma api for SDDM, because I had a lot of problems and errors right now.

**Comment by varlesh** [comment]
It's very strange why version 20220607 worked for you.
It's impossible with new Plasma version, because API very serious changed and more functions deprecated:
https://github.com/KDE/plasma-workspace/commit/3422348c5216078f598954c4b7c7e0fc902ce3b7
For example, function `onGraceLockedChanged()` now used as fallback (but from KScreenLocker only), and `"X-Plasma-APIVersion": "2"` - without this option loaded legacy API, but functions not worked...

See this test with 20220607 version:
![image](https://user-images.githubusercontent.com/8083855/176850573-6bb33d4b-0feb-4803-9c0b-5149637ffece.png)
It's not Materia - it's fallback KScreenLocker theme

**Comment by varlesh** [comment]
Please note that the same keyboard layout error is present in the logs

**Comment by varlesh** [comment]
Please note that the same keyboard layout error is present in the logs

**Comment by Dkoeddnsnp** [comment]
> 

Yes, when downgraded the kscreenlocker uses a fallback theme, which works without any issues for me under Wayland session. 

> I'm added Wayland Keyboard, maybe it's solved this problem? Please try it: [com.github.varlesh.materia-dark.zip](https://github.com/PapirusDevelopmentTeam/materia-kde/files/9027522/com.github.varlesh.materia-dark.zip)

I will try and test this.

**Comment by varlesh** [comment]
maybe need delete cache:
`rm -rf ~/.cache/plasm*`

**Comment by Dkoeddnsnp** [comment]
I tested your proposed version, downgraded fallback theme and stock breeze, and they all have this issue under Wayland. The broken lock screen happens (almost with 100% probability) after pressing some fast random combination of keys (Alt + Shift + Win + Ctrl). It did not occur under X11. So, it is not related to Materia KDE.

**Comment by varlesh** [comment]
Thank you for your thorough research. I think this is the problem of integrating Wayland into Plasma. But I'm not good at such complicated things :)
