### ISSUE TITLE
What happened with Adapta?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [PapirusDevelopmentTeam/materia-kde#156]
I think Adapta is simply the best KDE style there is. Its way better than Breeze, even if its just a very solid base for a monochrome iconset. The vectors are just amazing.

It is archived, and I am wondering why. I would like to maintain it, are there any others that want too? There are minimal errors, even though it works very well with Plasma 5.27.

Plasma 6 will probably be a challenge.

**Comment by SmartFinn** [comment]
The author of [Adapta GTK theme](https://github.com/adapta-project/adapta-gtk-theme) had released a new version (Adapta v4 if I remember it right), that had too much difference from the original theme, and he faced with tons of hate from his community. So he decided to kill the project https://github.com/adapta-project/adapta-gtk-theme/commit/4e74e0f569ed527b715ca3840f5d7701baebaf3c and direct his efforts to [Plata-theme](https://gitlab.com/tista500/plata-theme) (that looks exact as Adapta v4).

All of these KDE themes (Arc-KDE, Adapta-KDE, Materia-KDE) are solving one problem, it to hide differences between GTK and Qt apps to make UI/UX as close as possible. So developing Adapta-KDE without adapta-gtk-theme is nonsensical. That's why that project was frozen.

**Comment by boredsquirrel** [comment]
Thanks for the infos!
