### ISSUE TITLE
User-Selectable color variants? 

### ISSUE THREAD

**Issue by benjamindaines** [PapirusDevelopmentTeam/materia-kde#23]
Would you consider implementing a few different color variants?  I really like MateriaLight, but I'm really over the green check boxes and sliders.  I think blue would be very nice.  However, I think it would be very unfair for me to ask you to change the whole theme (which other people are probably greatly enjoying) for me.  

Thus, I think it would be great if you could supply a few different Materia*.svg files with different accent colors.  This would make the best Kvantum theme even better!  

I've been playing around, trying to edit the .svg file for my own colors and haven't really had luck.  This is mostly because I don't know how to use Inkscape or Karbon and Adobe AI doesn't seem to like your files. 

Anyway, thanks for all your hard work and hopefully I'll be looking at some cool blue accents soon!

**Comment by AryToNeX** [comment]
The accent should be clearly defined in the SVG and be easily editable imho, since the defs section in the SVG files does exist. @varlesh

**Comment by varlesh** [comment]
I'm not planned support multipy colors, because Kvantum not support KDE Color Scheme...
But you can modify sources for my self... all elements opensource.

Also Materia KDE  - it's port GTK Materia theme for KDE and we use colors from GTK.
Our main idea - single style and uniform KDE/Qt with GTK!!!

Green (teal) colors used on GTK sliders and checkbox:
![image](https://user-images.githubusercontent.com/8083855/51131875-4f624e80-184a-11e9-8c32-985aec7d9fe1.png)
