### ISSUE TITLE
drop down menu icon not visible

### ISSUE THREAD

**Issue by foss1111** [PapirusDevelopmentTeam/materia-kde#68]
little drop down icon not visible in both materia and adapta kvantum theme(screenshot1)
it is visible in [kvadapta]( https://github.com/tsujan/Kvantum/tree/master/Kvantum/themes/kvthemes/KvAdaptaDark)(screenshot2) theme though..
![Screenshot_20191019_220712](https://user-images.githubusercontent.com/56786696/67157338-6fc6b880-f348-11e9-9811-224711c176c0.png)

![screenshotkvadapta](https://user-images.githubusercontent.com/56786696/67157399-02675780-f349-11e9-950f-d9650e67578c.jpg)

**Comment by varlesh** [comment]
It's not bug. This icon specially hidden, because takes up usable space (If you use Toolbar panel on verticaly):
![image](https://user-images.githubusercontent.com/8083855/67157756-d72d3a00-f341-11e9-9f5f-b306bf615ae8.png)
![image](https://user-images.githubusercontent.com/8083855/67157767-ef9d5480-f341-11e9-8d57-1d3b258251ff.png)
But you can enable this, if you want. Open config file, find section `[PanelButtonTool]` and replace `indicator.size=0` to `indicator.size=8`

**Comment by foss1111** [comment]
Thanks for clarification...
