### ISSUE TITLE
kvantum materia theme use bad color  for toolbar

### ISSUE THREAD

**Issue by hosxy** [PapirusDevelopmentTeam/materia-kde#72]
toolbar can't see clearly. 
![深度截图_选择区域_20200101160648](https://user-images.githubusercontent.com/17108640/71639395-d3f2ea80-2cb0-11ea-806a-abf3048117ae.png)
![深度截图_选择区域_20200101160517](https://user-images.githubusercontent.com/17108640/71639396-d7867180-2cb0-11ea-8c2e-85d455ce59dc.png)

**Comment by varlesh** [comment]
not confirm this:
![image](https://user-images.githubusercontent.com/8083855/71641332-a6f40700-2cb3-11ea-818d-fd8e564ab2fa.png)
Kvantum version?

**Comment by hosxy** [comment]
> not confirm this:
> ![image](https://user-images.githubusercontent.com/8083855/71641332-a6f40700-2cb3-11ea-818d-fd8e564ab2fa.png)
> Kvantum version?

You are right, I find this is icon theme's problem.
I am so sorry

**Comment by afraidofmusic** [comment]
I think it's because in the GTK theme, the toolbar isn't dark; only the menubar is dark.

Tranmission-GTK and Transmission-QT
![Screenshot from 2020-06-25 14-42-42](https://user-images.githubusercontent.com/25895258/85713733-3285a800-b6d9-11ea-95bc-6088321c3c6a.png)

Dolphin
![Screenshot from 2020-06-25 14-46-35](https://user-images.githubusercontent.com/25895258/85714143-a922a580-b6d9-11ea-9e55-bf31b08ce088.png)

I hope it's relevant even though I'm using Gnome
